name: pokedex
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  openapi_generator_annotations: ^6.1.0
  pokedex_api:
    path: ./api/pokedex_api

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  openapi_generator: ^6.1.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
